# Generated by Django 3.2.9 on 2022-01-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
    ]
